Enable BUILD_ARM64_DT_OVERLAY and disable CONFIG_MODULE_SIG_FORCE
- Fix following error by enabling BUILD_ARM64_DT_OVERLAY
  Error: ../arch/arm64/boot/dts/qcom/sdm845-interposer-pm660.dtsi:
  157.1-16 Label or path led_flash_rear not found
  ...
  FATAL ERROR: Syntax error parsing input tree

- qca_cld3_wlan.ko in /vendor partition responsible wlan0 interface
  and thus Wi-Fi won't load due to 'Required key not available' (ENOKEY)
  error. CONFIG_MODULE_SIG_FORCE is disabled in defconfig to let this
  driver load. Dangerous. But, a work-around for now, to get going!